"""remove_price_updated_at_column

Revision ID: 0bc8b3e0580c
Revises: 58a2664e8dbb
Create Date: 2025-12-02 16:01:08.709575

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0bc8b3e0580c"
down_revision: Union[str, Sequence[str], None] = "58a2664e8dbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gold_prices_updated_at"), table_name="gold_prices")
    op.drop_column("gold_prices", "price_updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gold_prices",
        sa.Column(
            "price_updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_gold_prices_updated_at"),
        "gold_prices",
        ["price_updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###
