"""add_professionals_table

Revision ID: 18ad15414c2e
Revises: 0bc8b3e0580c
Create Date: 2026-05-06 17:10:45.782013

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18ad15414c2e"
down_revision: Union[str, Sequence[str], None] = "0bc8b3e0580c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "professionals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("pronoun", sa.String(length=10), nullable=False),
        sa.Column("expert_name", sa.String(length=100), nullable=False),
        sa.Column("nationality", sa.String(length=50), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("id_number", sa.String(length=20), nullable=True),
        sa.Column("issued_date", sa.Date(), nullable=True),
        sa.Column("issued_place", sa.String(length=100), nullable=True),
        sa.Column("email_address", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("bank_account", sa.String(length=30), nullable=True),
        sa.Column("bank_name", sa.String(length=100), nullable=True),
        sa.Column("rate", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_professionals_expert_name", "professionals", ["expert_name"], unique=False
    )
    op.create_index(
        "ix_professionals_id_number", "professionals", ["id_number"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_professionals_id_number", table_name="professionals")
    op.drop_index("ix_professionals_expert_name", table_name="professionals")
    op.drop_table("professionals")
    # ### end Alembic commands ###
