"""Increase activity_number length to 2000

Revision ID: 328531f826bc
Revises: ba6e23125e91
Create Date: 2026-05-08 17:42:38.511241

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "328531f826bc"
down_revision: Union[str, Sequence[str], None] = "ba6e23125e91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expert_contract_activities") as batch_op:
        batch_op.alter_column(
            "activity_number",
            existing_type=sa.VARCHAR(length=20),
            type_=sa.String(length=2000),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expert_contract_activities") as batch_op:
        batch_op.alter_column(
            "activity_number",
            existing_type=sa.String(length=2000),
            type_=sa.VARCHAR(length=20),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
