"""update_gold_prices_table_structure

Revision ID: 58a2664e8dbb
Revises: 0421991f354c
Create Date: 2025-12-02 15:58:39.924472

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "58a2664e8dbb"
down_revision: Union[str, Sequence[str], None] = "0421991f354c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gold_prices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("location", sa.String(length=25), nullable=False),
        sa.Column("gold_type", sa.String(length=25), nullable=False),
        sa.Column("buy_price", sa.Float(), nullable=False),
        sa.Column("sell_price", sa.Float(), nullable=False),
        sa.Column("price_updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_gold_prices_date", "gold_prices", ["date"], unique=False)
    op.create_index(
        "ix_gold_prices_date_gold_type",
        "gold_prices",
        ["date", "gold_type"],
        unique=False,
    )
    op.create_index(
        "ix_gold_prices_gold_type", "gold_prices", ["gold_type"], unique=False
    )
    op.create_index(
        "ix_gold_prices_updated_at", "gold_prices", ["price_updated_at"], unique=False
    )
    op.drop_table("goldprice")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "goldprice",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("goldprice_pkey")),
    )
    op.drop_index("ix_gold_prices_updated_at", table_name="gold_prices")
    op.drop_index("ix_gold_prices_gold_type", table_name="gold_prices")
    op.drop_index("ix_gold_prices_date_gold_type", table_name="gold_prices")
    op.drop_index("ix_gold_prices_date", table_name="gold_prices")
    op.drop_table("gold_prices")
    # ### end Alembic commands ###
