"""add_professional_contracts

Revision ID: add_professional_contracts
Revises: 18ad15414c2e
Create Date: 2026-05-06

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a0d46eda88ae"
down_revision: Union[str, Sequence[str], None] = "18ad15414c2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "professional_contracts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.String(length=50), nullable=False),
        sa.Column("dd", sa.Integer(), nullable=False),
        sa.Column("mm", sa.Integer(), nullable=False),
        sa.Column("yyyy", sa.Integer(), nullable=False),
        sa.Column("abbreviated_project", sa.String(length=50), nullable=False),
        sa.Column("additional_information", sa.String(length=500), nullable=True),
        sa.Column("sum_activities", sa.String(length=500), nullable=True),
        sa.Column("activity_purpose", sa.String(length=255), nullable=True),
        sa.Column("project_name", sa.String(length=200), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("total_amount", sa.Float(), nullable=False, server_default="0"),
        sa.Column("tax", sa.Float(), nullable=False, server_default="0.1"),
        sa.Column("final_amount", sa.Float(), nullable=False, server_default="0"),
        sa.Column("professional_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["professional_id"],
            ["professionals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_contracts_professional_id",
        "professional_contracts",
        ["professional_id"],
        unique=False,
    )
    op.create_index(
        "ix_contracts_order_id",
        "professional_contracts",
        ["order_id"],
        unique=False,
    )

    op.create_table(
        "contract_activities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("activity_number", sa.String(length=20), nullable=False),
        sa.Column("activity_name", sa.String(length=200), nullable=False),
        sa.Column("budget", sa.String(length=100), nullable=True),
        sa.Column("working_days", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("rate", sa.Float(), nullable=False, server_default="0"),
        sa.Column("real_amount", sa.Float(), nullable=False, server_default="0"),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["professional_contracts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_activities_contract_id",
        "contract_activities",
        ["contract_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_activities_contract_id", table_name="contract_activities")
    op.drop_table("contract_activities")
    op.drop_index("ix_contracts_order_id", table_name="professional_contracts")
    op.drop_index(
        "ix_contracts_professional_id", table_name="professional_contracts"
    )
    op.drop_table("professional_contracts")
    # ### end Alembic commands ###
