"""Increase activity_name and budget length to 2000

Revision ID: ba6e23125e91
Revises: remove_expert_rate_column
Create Date: 2026-05-08 17:38:39.825955

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba6e23125e91"
down_revision: Union[str, Sequence[str], None] = "remove_expert_rate_column"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expert_contract_activities") as batch_op:
        batch_op.alter_column(
            "activity_name",
            existing_type=sa.VARCHAR(length=200),
            type_=sa.String(length=2000),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "budget",
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=2000),
            existing_nullable=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expert_contract_activities") as batch_op:
        batch_op.alter_column(
            "budget",
            existing_type=sa.String(length=2000),
            type_=sa.VARCHAR(length=100),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "activity_name",
            existing_type=sa.String(length=2000),
            type_=sa.VARCHAR(length=200),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
