"""initial_schema

Revision ID: be43a8988408
Revises: 
Create Date: 2026-06-25 17:25:28.269805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be43a8988408'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pronoun', sa.String(length=10), nullable=False),
    sa.Column('expert_name', sa.String(length=100), nullable=False),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('id_number', sa.String(length=20), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('issued_place', sa.String(length=100), nullable=True),
    sa.Column('email_address', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('bank_account', sa.String(length=30), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experts', schema=None) as batch_op:
        batch_op.create_index('ix_experts_expert_name', ['expert_name'], unique=False)
        batch_op.create_index('ix_experts_id_number', ['id_number'], unique=False)

    op.create_table('gold_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=25), nullable=False),
    sa.Column('gold_type', sa.String(length=25), nullable=False),
    sa.Column('buy_price', sa.Float(), nullable=False),
    sa.Column('sell_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gold_prices', schema=None) as batch_op:
        batch_op.create_index('ix_gold_prices_date', ['date'], unique=False)
        batch_op.create_index('ix_gold_prices_date_gold_type', ['date', 'gold_type'], unique=False)
        batch_op.create_index('ix_gold_prices_gold_type', ['gold_type'], unique=False)

    op.create_table('programs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('summary_activities', sa.String(length=500), nullable=True),
    sa.Column('activity_purpose', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_code')
    )
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_index('ix_programs_program_code', ['program_code'], unique=False)

    op.create_table('expert_contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('dd', sa.Integer(), nullable=False),
    sa.Column('mm', sa.Integer(), nullable=False),
    sa.Column('yyyy', sa.Integer(), nullable=False),
    sa.Column('abbreviated_project', sa.String(length=50), nullable=False),
    sa.Column('additional_information', sa.String(length=500), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('final_amount', sa.Float(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expert_contracts', schema=None) as batch_op:
        batch_op.create_index('ix_contracts_expert_id', ['expert_id'], unique=False)
        batch_op.create_index('ix_contracts_program_id', ['program_id'], unique=False)
        batch_op.create_index('ix_expert_contracts_order_id', ['order_id'], unique=False)

    op.create_table('expert_contract_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_number', sa.String(length=2000), nullable=False),
    sa.Column('activity_name', sa.String(length=2000), nullable=False),
    sa.Column('budget', sa.String(length=2000), nullable=True),
    sa.Column('working_days', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('real_amount', sa.Float(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['expert_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expert_contract_activities', schema=None) as batch_op:
        batch_op.create_index('ix_expert_contract_activities_contract_id', ['contract_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expert_contract_activities', schema=None) as batch_op:
        batch_op.drop_index('ix_expert_contract_activities_contract_id')

    op.drop_table('expert_contract_activities')
    with op.batch_alter_table('expert_contracts', schema=None) as batch_op:
        batch_op.drop_index('ix_expert_contracts_order_id')
        batch_op.drop_index('ix_contracts_program_id')
        batch_op.drop_index('ix_contracts_expert_id')

    op.drop_table('expert_contracts')
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index('ix_programs_program_code')

    op.drop_table('programs')
    with op.batch_alter_table('gold_prices', schema=None) as batch_op:
        batch_op.drop_index('ix_gold_prices_gold_type')
        batch_op.drop_index('ix_gold_prices_date_gold_type')
        batch_op.drop_index('ix_gold_prices_date')

    op.drop_table('gold_prices')
    with op.batch_alter_table('experts', schema=None) as batch_op:
        batch_op.drop_index('ix_experts_id_number')
        batch_op.drop_index('ix_experts_expert_name')

    op.drop_table('experts')
    # ### end Alembic commands ###
